sudo: true

language: python

python:
  - 3.5
  - 3.6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-6; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - echo g++-6 --version
# Force use of modern pip and setuptools
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -r requirements.txt --verbose
  - python -V


install:
  - pip install . --verbose

script:
  - mkdir empty
  - cd empty
  - python -c "import sys; import pyfastnoisesimd; sys.exit(0 if pyfastnoisesimd.test().wasSuccessful() else 1)"

notifications:
  email: false


